import "bootstrap/dist/css/bootstrap.min.css"; // Import Bootstrap CSS
import { DevtoolsProvider } from "@providers/devtools";
import { GitHubBanner, Refine  } from "@refinedev/core";
import { RefineKbar, RefineKbarProvider} from "@refinedev/kbar";
import routerProvider from "@refinedev/nextjs-router";
import { Metadata } from "next";
import React, { Suspense } from "react";
import { resources } from "@resources/resources";

import { dataProvider } from "@providers/data-provider";
import "@styles/global.css";

export const metadata: Metadata = {
  title: "Refine",
  description: "Generated by create refine app",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({children,}: Readonly<{ children: React.ReactNode;}>) {

  return (
    <html lang="en">
      <body>
        <Suspense>
          <GitHubBanner />
          <RefineKbarProvider>
            <DevtoolsProvider>
             
              <Refine
         
                routerProvider={routerProvider}
                dataProvider={dataProvider}
                resources={resources}
                options={{
                  syncWithLocation: true,
                  warnWhenUnsavedChanges: true,
                  useNewQueryKeys: true,
                  projectId: "LquuDr-3pcqu1-VGiC0A",
                }}
              >
                {children}
                <RefineKbar />
              </Refine>
      
            </DevtoolsProvider>
          </RefineKbarProvider>
        </Suspense>
      </body>
    </html>
  );
}
