apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tickets-log-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi  # Adjust the size based on your needs
  storageClassName: standard  # Ensure this matches your cluster's storage cl